stages:
  - test
  - build
  - editors
  - doc
  - release
  - publish
variables:
  GITLAB_HOST: gitlab.ppidev.net
  RELEASE_TOKEN: $RELEASE_TOKEN
  GLAB_SEND_TELEMETRY: false
  GODEBUG: "invalidptr=0,cgocheck=0"
  KUBERNETES_CPU_REQUEST: "1"
  KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "8Gi"
  KUBERNETES_MEMORY_REQUEST: "6Gi"
  JSONNET_VERSION: "v0.21.0"
  JSONNET_VERSION_NODE: "v0.20.0"
  GOLANG_IMAGE: golang
  GOLANG_VERSION: 1.24

include:
  - project: ct/admin/pipeline/default-pipelines
    ref: master
    file:
      - base/image-jobs.yml
      - base/generic-artifacts-jobs.yml

.set-version: &set-version cargo install cargo-set-version && cargo set-version ${CI_COMMIT_TAG:-0.0.0}

conform:
  stage: test
  image: ${GOLANG_IMAGE}:${GOLANG_VERSION}
  variables:
    GOBIN: "/usr/bin"
  before_script:
    - go install github.com/siderolabs/conform/cmd/conform@latest
  script:
    - conform enforce --base-branch main~1

test:
  image: rust:latest
  stage: test
  variables:
    GOBIN: "/usr/bin"
  before_script:
    - apt-get update && apt-get -y install clang golang
    - go install github.com/google/go-jsonnet/cmd/jsonnet@${JSONNET_VERSION}
    - rustup toolchain install nightly
    - rustup default nightly
    - cargo install --root . cargo2junit cargo-tarpaulin
  script:
    - bin/cargo-tarpaulin --tests --out xml --engine llvm --  -Z unstable-options --format=json | bin/cargo2junit > report.xml
  coverage: '/^\d+.\d+% coverage/'
  artifacts:
    when: always
    reports:
      junit:
        - report.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

build:linux:
  stage: build
  image: rust:latest
  artifacts:
    paths:
      - target/release/grustonnet-ls
      - target/release/grustonnet-lint
      - schema.json
  variables:
    GOBIN: "/usr/bin"
  before_script:
    - *set-version
    - apt-get update && apt-get -y install clang golang
    - go install github.com/google/go-jsonnet/cmd/jsonnet@${JSONNET_VERSION}
  script:
    - cargo build --release
    # Save a bunch of download and a stage by just creating the schema here
    - ./target/release/grustonnet-ls --export-config-schema > schema.json

build:windows:
  stage: build
  image: rust:latest
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/grustonnet-ls.exe
      - target/x86_64-pc-windows-gnu/release/grustonnet-lint.exe
  variables:
    GOBIN: "/usr/bin"
  before_script:
    - *set-version
    - apt-get update && apt-get -y install clang golang gcc-mingw-w64
    - go install github.com/google/go-jsonnet/cmd/jsonnet@${JSONNET_VERSION}
    - rustup target add x86_64-pc-windows-gnu
  script:
    - cargo build --release --target x86_64-pc-windows-gnu

editors:intellij:
  stage: editors
  image: rust:latest
  dependencies:
    - "build:linux"
  artifacts:
    paths:
      - lsp4ij.tar.gz
  variables:
    GOBIN: "/usr/bin"
    EDITOR_PATH: "editors/intellij"
    KUBERNETES_CPU_REQUEST: "100m"
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "1Gi"
    KUBERNETES_MEMORY_REQUEST: "1Gi"
  before_script:
    - apt-get update && apt-get -y install golang
    - go install github.com/google/go-jsonnet/cmd/jsonnet@${JSONNET_VERSION}
  script:
    - ./target/release/grustonnet-ls --export-config-schema > $EDITOR_PATH/settings.schema.json
    - mkdir out && jsonnet -m out ${EDITOR_PATH}/template.jsonnet
    - tar cfz lsp4ij.tar.gz -C out .

rustdoc:
  stage: doc
  image: rust
  variables:
    GOBIN: "/usr/bin"
    KUBERNETES_CPU_REQUEST: "100m"
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "1Gi"
    KUBERNETES_MEMORY_REQUEST: "1Gi"
  before_script:
    - apt-get update && apt-get -y install clang golang
    - go install github.com/google/go-jsonnet/cmd/jsonnet@${JSONNET_VERSION}
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc
  only:
    - main

mdbook:
  stage: doc
  image: nixos/nix
  variables:
    KUBERNETES_CPU_REQUEST: "100m"
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "8Gi"
    KUBERNETES_MEMORY_REQUEST: "2Gi"
  timeout: 2h
  script:
    - echo "experimental-features = nix-command flakes" > /etc/nix/nix.conf
    - cd docs
    - nix develop . --command make
  artifacts:
    paths:
      - docs/book
  only:
    - main

changelog:
  image:
    name: orhunp/git-cliff:latest
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_TAG
  dependencies: []
  variables:
    GIT_STRATEGY: clone # clone entire repo instead of reusing workspace
    GIT_DEPTH: 0 # avoid shallow clone to give cliff all the info it needs
  stage: doc
  script:
    - git-cliff -r . --current > CHANGELOG.md
  artifacts:
    paths:
      - CHANGELOG.md

release_job:
  stage: release
  image: gitlab/glab:latest
  variables:
    KUBERNETES_CPU_REQUEST: "100m"
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "1Gi"
    KUBERNETES_MEMORY_REQUEST: "1Gi"
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - glab auth login --token ${RELEASE_TOKEN} --hostname ${GITLAB_HOST}
    - glab release create ${CI_COMMIT_TAG} -F CHANGELOG.md
    - tar cfz grustonnet_ls_windows_amd64.tar.gz -C target/x86_64-pc-windows-gnu/release . && glab release upload ${CI_COMMIT_TAG} grustonnet_ls_windows_amd64.tar.gz
    - tar cfz grustonnet_ls_linux_amd64.tar.gz -C target/release . &&  glab release upload ${CI_COMMIT_TAG} grustonnet_ls_linux_amd64.tar.gz
    - glab release upload ${CI_COMMIT_TAG} lsp4ij.tar.gz

release:grustonnet-ls:
  extends: .CTSI_upload-generic-file
  stage: release
  variables:
    CIY_ARTIFACT_SOURCE_PATH: target/release/grustonnet-ls
    CIY_ARTIFACT_TARGET_PATH: de/ppi/std/grustonnet-ls/${CI_COMMIT_TAG}-grustonnet-ls
    CIY_GENERIC_REPO_NAME: std-generic-dmz
  rules:
    - if: $CI_COMMIT_TAG

release:grustonnet-ls-windows:
  extends: .CTSI_upload-generic-file
  stage: release
  variables:
    CIY_ARTIFACT_SOURCE_PATH: target/x86_64-pc-windows-gnu/release/grustonnet-ls.exe
    CIY_ARTIFACT_TARGET_PATH: de/ppi/std/grustonnet-ls/${CI_COMMIT_TAG}-grustonnet-ls.exe
    CIY_GENERIC_REPO_NAME: std-generic-dmz
  rules:
    - if: $CI_COMMIT_TAG

release:grustonnet-ls-latest:
  extends: .CTSI_upload-generic-file
  stage: release
  variables:
    CIY_ARTIFACT_SOURCE_PATH: target/release/grustonnet-ls
    CIY_ARTIFACT_TARGET_PATH: de/ppi/std/grustonnet-ls/grustonnet-ls
    CIY_GENERIC_REPO_NAME: std-generic-dmz
  rules:
    - if: $CI_COMMIT_TAG

release:grustonnet-ls-windows-latest:
  extends: .CTSI_upload-generic-file
  stage: release
  variables:
    CIY_ARTIFACT_SOURCE_PATH: target/x86_64-pc-windows-gnu/release/grustonnet-ls.exe
    CIY_ARTIFACT_TARGET_PATH: de/ppi/std/grustonnet-ls/grustonnet-ls.exe
    CIY_GENERIC_REPO_NAME: std-generic-dmz
  rules:
    - if: $CI_COMMIT_TAG

pages:
  stage: publish
  image: alpine
  dependencies:
    - rustdoc
    - mdbook
  variables:
    KUBERNETES_CPU_REQUEST: "100m"
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "1Gi"
    KUBERNETES_MEMORY_REQUEST: "1Gi"
  script:
    - mkdir -p public
    - mv target/doc public/doc
    - mv docs/book public/book
  artifacts:
    paths:
      - public
  only:
    - main

build-image:grustonnet:
  needs:
    - build:linux
  extends: .CTSI_build-image

release-image:grustonnet:
  extends: .CTSI_release-image
