default_install_hook_types:
  - commit-msg
  - post-commit
  - pre-push
repos:
  - repo: https://github.com/siderolabs/conform
    rev: "8584940"
    hooks:
      - id: conform
        stages:
          - commit-msg
          - post-commit # for signing
  - repo: local
    hooks:
      - id: conform
        name: conform
        language: system # change to "unsupported" with newer versions
        stages:
          - pre-push
        entry: make conform
      - id: test
        name: test
        language: system # change to "unsupported" with newer versions
        stages:
          - pre-push
        entry: make test
      - id: clippy
        name: clippy
        language: rust
        stages:
          - pre-push
        entry: make clippy
