[workspace.package]
version = "0.2.0"
edition = "2024"

[profile.release]
strip = true
lto = true

[workspace.lints.clippy]
uninlined_format_args = "allow"
needless_update = "allow"

[workspace]
members = [
"crates/grustonnet-bin",
"crates/grustonnet-ls-lib",
"crates/jsonnet-bridge",
"crates/jsonnet-location",
"crates/language-server",
"crates/test-macros",
]
resolver = "3"

