[package]
name = "jsonnet-cst"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
tree-sitter = "0.25.10"
tree-sitter-jsonnet = {git = "https://github.com/koskev/tree-sitter-jsonnet"}
jsonnet-location = { path = "../jsonnet-location"}
ropey = "1.6.1"
log = "0.4.27"
language-server = { path = "../language-server"}
